### ISSUE TITLE
Support Alfred 4

### ISSUE THREAD

**Issue by vivaxy** [sindresorhus/alfy#110]
```sh
npm install --global alfred-lock
```

Errors:

```
> alfred-lock@2.0.0 postinstall /Users/vivaxy/.npm-packages/lib/node_modules/alfred-lock
> alfy-init

{ Error: Command failed: alfred-link
Error: Alfred preferences not found at location /Users/vivaxy/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist
    at pathExists.then.exists (/Users/vivaxy/.npm-packages/lib/node_modules/alfred-lock/node_modules/resolve-alfred-prefs/index.js:15:10)


    at makeError (/Users/vivaxy/.npm-packages/lib/node_modules/alfred-lock/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/Users/vivaxy/.npm-packages/lib/node_modules/alfred-lock/node_modules/execa/index.js:278:16)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
  code: 1,
  stdout: '',
  stderr:
   'Error: Alfred preferences not found at location /Users/vivaxy/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n    at pathExists.then.exists (/Users/vivaxy/.npm-packages/lib/node_modules/alfred-lock/node_modules/resolve-alfred-prefs/index.js:15:10)\n',
  failed: true,
  signal: null,
  cmd: 'alfred-link',
  timedOut: false,
  killed: false }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alfred-lock@2.0.0 postinstall: `alfy-init`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the alfred-lock@2.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vivaxy/.npm/_logs/2019-05-31T14_25_10_280Z-debug.log
```

**Comment by sindresorhus** [comment]
Can you please include an issue description? Is there anything that needs to change for Alfred 4?

**Comment by bnavetta** [comment]
Started running into this as well. Alfred 4 moved the preferences, so workflows are now at `~/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows` instead of `~/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows`. It might be [SamVerschueren/resolve-alfred-prefs](https://github.com/SamVerschueren/resolve-alfred-prefs) that needs to change, since that's what `alfred-link` uses.

**Comment by raisedadead** [comment]
More precisely this linked issue needs to be addressed: https://github.com/SamVerschueren/resolve-alfred-prefs/issues/7

But its worth keeping the issue on this repo open as well for discoverability.

**Comment by raisedadead** [comment]
Meanwhile I found a workaround to resolve this temporarily by creating a symlink:

```sh
ln -s ~/Library/Preferences/com.runningwithcrayons.Alfred-Preferences.plist ~/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist
```

This of course assumes that you have only Alfred 4 installed and not any other older version

**Comment by LitoMore** [comment]
I think we should add support for both 3 and 4, it should be returned two results if both of Alfred 3 and Alfred 4 exist.

I left a comment here: https://github.com/SamVerschueren/resolve-alfred-prefs/pull/5#issuecomment-499393788.

**Comment by LitoMore** [comment]
Now Alfy supports Alfred 4, [alfred-link](https://github.com/SamVerschueren/alfred-link) has been released a patch update to add support for Alfred 4. Just update your dependencies to get it to work. 😄

**Comment by vivaxy** [comment]
Problem solved, Thanks!

**Comment by Arro** [comment]
As an add-on to @raisedadead 's comment above, I also needed to run the following command:

`ln -s ~/Library/Application\ Support/Alfred ~/Library/Application\ Support/Alfred\ 3`

FWIW, I install Alfred 4 via homebrew, so maybe that's part of the issue.
