### ISSUE TITLE
Is Typescript declaration provided for alfy?

### ISSUE THREAD

**Issue by Troublor** [sindresorhus/alfy#126]

**Comment by sindresorhus** [comment]
I think you could have easily checked this yourself instead of asking.

**Comment by Troublor** [comment]
Yes I checked with `yarn add --dev @types/alfy` and it was 404. 
I was asking in case there you have already implemented the declarations but not published as `@types/alfy`......

I notice a new issue #127 has just been created to call for type declaration contributions. I guess the answer is no.
