### ISSUE TITLE
Getting alfy-init: command not found

### ISSUE THREAD

**Issue by urre** [sindresorhus/alfy#130]
I was about to make an update to my [Alfredinary](https://github.com/urre/alfredinary), but now getting `alfy-init: command not found`. I have `"postinstall": "alfy-init",` in my `package.json`.

Using Node.js v14.8.0, Alfred 4.3.2 and these are my dependencies to the Alfred workflow

```
  "dependencies": {
    "alfy": "^0.10.0",
    "cloudinary": "^1.25.0",
    "dotenv": "^8.2.0"
  }
```

**Comment by urre** [comment]
Running this manually seems to work: `./node_modules/alfy/init.js`

**Comment by sindresorhus** [comment]
Sounds like an npm issue. https://github.com/sindresorhus/alfy/blob/5962de4d4a356c55cd11727369613a04a96dbce7/package.json#L9 is correctly defined.

**Comment by urre** [comment]
Yea I thought everything looked good. Wonder why I'm getting "command note found" on this.
