### ISSUE TITLE
run failed if index.js is esm module

### ISSUE THREAD

**Issue by JiangWeixian** [sindresorhus/alfy#139]
### error

[ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/jiangwei/.nvm/versions/node/v14.17.3/lib/node_modules/@ifu/emoji/index.js
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13) {
  code: 'ERR_REQUIRE_ESM'
}

node: v14.17.3
alfy: 0.11.1

i try to remove `--require esm` in `run-node.sh`, will not throw this error anymore. so what `--require esm` doing

**Comment by sindresorhus** [comment]
Should be fixed in https://github.com/sindresorhus/alfy/releases/tag/v0.12.0
