### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/alfy#19]
The tests are flaky because of these two lines
- [test/cache.js#L8](https://github.com/sindresorhus/alfy/blob/master/test/cache.js#L8)
- [test/fetch.js#L11](https://github.com/sindresorhus/alfy/blob/master/test/fetch.js#L11)

They are both working on the same instance of `CacheConf`. Is there anyway we can work around this problem without merging everything in one test file or run the test serially?

**Comment by sindresorhus** [comment]
Yeah, we could prepend `+ Date.now()` to https://github.com/sindresorhus/alfy/blob/7e0f7c7dbbbff427e856a0b6ade02f4e54d629d7/index.js#L99
