### ISSUE TITLE
Prevent cache failures on workflow update

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/alfy#23]
I was implementing the `transform` function of the `alfy.fetch` method in `alfred-ng2` and noticed a subtle area that could cause your workflow from failing a certain amount of time due to the cache being invalid.

Let me give you an example first to make it easier to understand. Let's assume I was calling an XML API that I transformed to JSON. At first (pre-transform), it would look like this.

```js
alfy.fetch(`https://my-api.com/resources.xml`, {maxAge: ONE_WEEK})
    .then(result => xml2js(result))
    .then(jsonResult => {
         // transform the jsonResult to alfred items
    });
```

The *XML* data is cached for one day. Now let's assume I upgrade to the transform function. This could be beneficiel because it only has to run the `xml2js` call once before caching.

```js
alfy.fetch(`https://my-api.com/resources.xml`, {
    maxAge: ONE_WEEK,
    transform: result => xml2js(result)
})
.then(jsonResult => {
    // transform the jsonResult to alfred items
});
```

An important thing to notice here is that in the second example, not the XML result is cached, but the result of the transform function and thus the JSON result is being cached. Pretty straightforward.

BUT, without knowing it, we could break everyones workflow now for one day. The thing is that if I had used this workflow quite recently, the XML data would still be cached and the `fetch` promise will not return JSON but XML. Boom, workflow explodes! Adding a function to (`transform` in this case), doesn't change anything to the [cache key](https://github.com/sindresorhus/alfy/blob/master/index.js#L124).

How did I solve this? By adding a `version` property to the options object.

```js
alfy.fetch(`https://my-api.com/resources.xml`, {
    maxAge: ONE_WEEK,
    version: pkg.version,
    transform: result => xml2js(result)
})
.then(jsonResult => {
    // transform the jsonResult to alfred items
});
```

This will make sure that my cache key is different on every release and will invalidate the old cache.

Is this something we could add in `alfy`? Could we detect the callers package.json version number? In my case `alfred-ng2` so that the developer doesn't have to worry about this issue? I'm quite sure that this issue will be overlooked by almost everyone if it was not tested properly.

A downside of this is that the cache could grow quite rapidly depending on the release cycles of the workflow.

**Comment by SamVerschueren** [comment]
Another approach I just realised is that we can add the current version number as part of the cached data. So instead of only caching the response, we could cache response + workflow version. Then we could simply invalidate/overwrite the cache if the version in the cache does not match the current workflow version. This way we prevent the cache from growing to infinity :).

**Comment by sindresorhus** [comment]
I like idea of invalidating the cache on workflow version mismatch. Could use [`alfy.meta.version`](https://github.com/sindresorhus/alfy#meta).

**Comment by SamVerschueren** [comment]
Aha sweet, totally missed that property :). Will do a PR later today.
