### ISSUE TITLE
Embed alfred-notifier

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/alfy#24]
It would totally make sense to embed [alfred-notifier](https://github.com/SamVerschueren/alfred-notifier). It's easy to miss the possibility of notifying your users when you have a new version, no one reads the docs (entirely). Notifying your users of a new version is best practice after all and I always want to know if a new version is available.

However, there should always be a way to turn this feature off. The question is, how? Some ways I can think off.

1. `alfy.disableUpdateNotification()`
2. `alfy.configure({updateNotification: false});`

**Comment by sindresorhus** [comment]
Let's go with `2`. We might want other options in the future.

**Comment by sindresorhus** [comment]
This also made me think, should we also bundle `alfred-link` here, to make it a fully featured experience out of the box? We could depend on `alfred-link` and just proxy it in a binary here as `alfy-setup`/`alfy-init` (we might want to do other things in the future, so could be useful to have a generic name).

**Comment by SamVerschueren** [comment]
> Let's go with 2. We might want other options in the future.

My thoughts exactly!

> Should we also bundle `alfred-link` here

Yes sure, why not. One dependency instead of 3 would be a very nice improvement.

**Comment by SamVerschueren** [comment]
Ok, I started looking into this and I think we have to rethink the way we want to do this.

My first thought was that we just put `alfredNotification()` at the top of the index file and we're done. But, we have to have a way of disabling this behaviour (see `alfy.configure()`).

### Option 1 - Opt-in

Instead of opt-out, we also could go for opt-in and offer a `alfy.updateNotification()` method. Rather have an opt-out though because this might be easily forgotten.

### Option 2 - output

Run the `alfredNotification()` method in the `alfy.output()` method which will be used in all the workflows, or am I wrong here?

### Option 3 - cli flag

Disable the behaviour in the workflow script with a flag (which is default `true`).

```
$ run-node index.js --no-notification
```

Downside is, we will have to parse this flag. We could also go for an environment variable.

### Option 4

Add an `alfy` section to `package.json` with some config options.

```json
{
    "name": "alfred-ng2",
    "version": "0.4.0",
    "alfy": {
        "disableNotification": true
    }
}
```
---------------------
My favorite is option number 4 to be honest. Easy to configure for users, easily understandable and easy to add new options for the future.

**Comment by SamVerschueren** [comment]
I checked what `read-pkg-up` does when executed within Alfy, and it just returns the workflow `package.json`. So number 4 would be perfectly possible.

**Comment by sindresorhus** [comment]
Let's go with 4.

`"disableNotification": true` => `"updateNotification": false`
