### ISSUE TITLE
ERROR: alfred.workflow.input.scriptfilter

### ISSUE THREAD

**Issue by follyxing** [sindresorhus/alfy#29]
[ERROR: alfred.workflow.input.scriptfilter] XML Parse Error 'The operation couldn’t be completed. (NSXMLParserErrorDomain error 4.)'. Row (null), Col (null): 'Document is empty' in XML:

index.js code:

```javascripe
const alfy = require('alfy');
alfy.output([{
        title: 'Unicorn'
}, {
        title: 'Rainbow'
}]);
```

**Comment by SamVerschueren** [comment]
Could you give is some more information? What did you use as starting point? Do you have an `info.plist` file?

If you didn't use it before, I suggest using the Yeoman generator, [generator-alfred](https://github.com/SamVerschueren/generator-alfred). This puts everything into place for you.

**Comment by follyxing** [comment]
Alfred 2 ... Sorry
