### ISSUE TITLE
Built version caching into CacheConf

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/alfy#34]
Currently, `alfy.fetch` will invalidate the cache if you update your workflow which is pretty nice. But maybe we should built this into [cache-conf](https://github.com/SamVerschueren/cache-conf). The reason I'm thinking about this is because I'm creating a new workflow that does not fetch the data from a server, but from different files in a dependency. Reading all those files and transforming the data takes some time and I want to cache it. But if I want to do it correctly, I will have to write the versioned caching myself. So maybe we should add an optional `version` property to `cache-conf` which will invalidate older caches and just overwrite them.

Another suggestion of fixing this is if we would allow to read local files with `alfy.fetch` as well.

```js
alfy.fetch('my-file.json', {
    maxAge: ONE_DAY,
    transform: data => {
       return {data};
    }
});
```

This way you will have the same benefits as URLs but for local files, as well as the transform function. Maybe this suggestion is a separate enhancement from the initial idea. But either one of them would solve my use case.

**Comment by SamVerschueren** [comment]
It's actually not that hard to implement yourself though https://github.com/SamVerschueren/alfred-aws/blob/master/index.js#L7-L22.

**Comment by sindresorhus** [comment]
Yes. Makes sense to have a `version` option.

-

> Another suggestion of fixing this is if we would allow to read local files with alfy.fetch as well.

Hmm. Maybe we should add some methods for reading/writing to disk with caching too? Just for ease of use.

**Comment by SamVerschueren** [comment]
Currently, I fixed my use case differently. Because all I had was static data, it makes way more sense to create a [make](https://github.com/SamVerschueren/alfred-aws/blob/master/make.js) script that generates a [data.json](https://github.com/SamVerschueren/alfred-aws/blob/master/data.json) file where the data already is preparsed. So maybe the reading/writing methods don't make much sense. Can't really come up with a use case at the moment.

The `version` option in `cache-conf` however might be really useful. I will create an issue over there and have a look when I find the time.

**Comment by SamVerschueren** [comment]
`cache-conf@0.3.0` has the new `version` property so this one can be fixed. Will do it in one of the following days.
