### ISSUE TITLE
How can i output a function?

### ISSUE THREAD

**Issue by Rawnly** [sindresorhus/alfy#47]
Hello! How can i run a function (for example **execa**) when user select an item from list?

That's my code:
```js
alfy.output([
	{
		title: 'Random',
		body: 'Get random photo'
	}, {
               title: 'ID',
               body: 'Pick photo by id'
        }
])  
```

Maybe not quite understand how it works

**Comment by SamVerschueren** [comment]
Link your alfred locally (`./node_modules/.bin/alfy-init`). Open `Alfred` and open the `Workflows` section and open your workflow.

You will now see something like this
<img width="845" alt="screen shot 2017-03-04 at 20 46 11" src="https://cloud.githubusercontent.com/assets/1913805/23581774/a78163fa-011b-11e7-8e91-19b0b16ab7a1.png">

Currently, by default the script passes the selected option to the `Open URL` action. However, you can remove that action and add another one by right-clicking the screen, `Actions` -> `Run Script`. A popup will apear and you can enter a bash command, or if you want to handle it with Node.js, the following script should work as well.

```js
./node_modules/.bin/run-node handler.js "$1"
```

Where `handler.js` is a file in your project

Connect both of them and you're good to go.

<img width="846" alt="screen shot 2017-03-04 at 20 49 39" src="https://cloud.githubusercontent.com/assets/1913805/23581794/1cd32d64-011c-11e7-9a69-a49a22543cda.png">

---------------------------------------
So how do you pass data from your search view to the `handler.js` file? Quite simple by adding an `arg` property to your output list.

```js
alfy.output([
	{
		title: 'Random',
		body: 'Get random photo',
                arg: 'rand'
	}, {
               title: 'ID',
               body: 'Pick photo by id',
               arg: 'id'
        }
])  
```

And in your `handler.js`, get the `arg` value like so

```js
const arg = process.argv[2];

if (arg === 'rand') {
    // Get a random picture
}
```

**Comment by SamVerschueren** [comment]
Yesterday I made [alfred-fkill](https://github.com/SamVerschueren/alfred-fkill) which uses the exact same workflow as I describe above. It might give you some inspiration :).

**Comment by Rawnly** [comment]
Thank you very much!
