### ISSUE TITLE
Access environment variables

### ISSUE THREAD

**Issue by artivilla** [sindresorhus/alfy#55]
#36 will likely resolve my issue so I can gather the users token to use to make API calls but for the short term is there a way to I can access the users system env variables?

**Comment by sindresorhus** [comment]
`process.env`?

**Comment by artivilla** [comment]
So this should work? `alfy.output([{ title: process.env.NVM_DIR }]);` Is there a way to console.log this without using alfy.output()?

**Comment by sindresorhus** [comment]
Yes, you could `console.error(process.env.NVM_DIR)` and check the debug panel in your workflow in Alfred.

**Comment by sindresorhus** [comment]
I guess we could add a `alfred.debug()` method.

**Comment by sindresorhus** [comment]
Just curious, why do you need `process.env.NVM_DIR`?

**Comment by artivilla** [comment]
Just an example, I wanted to have the user set the GITHUB_API_TOKEN locally so they can make API calls to their repos. Requires auth. Let me know if you know a diff way I can accomplish the same task? And thank you for all your hard work!

**Comment by artivilla** [comment]
Oh nice, I didn't know there way a debug panel. 🙃 That should be sufficient. Maybe we can add that to the docs?! I can put up a PR if you prefer.

**Comment by sindresorhus** [comment]
> I can put up a PR if you prefer.

👍

**Comment by sindresorhus** [comment]
Actually, I can handle it.

**Comment by sindresorhus** [comment]
Done: https://github.com/sindresorhus/alfy/pull/56

**Comment by sindresorhus** [comment]
> Let me know if you know a diff way I can accomplish the same task?

That's the best way until #36 is implemented.
