### ISSUE TITLE
Using `npm-registry-client` with alfy

### ISSUE THREAD

**Issue by artivilla** [sindresorhus/alfy#57]
I don't think this is an alfy issue but since this was the only way to reach you, I thought I'd post my question here.

To clarify, [npm registry client](https://github.com/npm/npm-registry-client) is built to work with the browser only and I can't use their request methods?

Easiest to just highlight the work -- I've marked out most of it but this method is trying to fetch npm starred repos: https://github.com/artivilla/alfred-starred/blob/master/index.js#L28

Using postman, I get this response:
`{"rows":[{"value":"basscss"},{"value":"bl"},{"value":"bluebird"},{"value":"fetch"},{"value":"jest-serializer-enzyme"},{"value":"json-web-token"},{"value":"kue"},{"value":"longjohn"},{"value":"mongoose-softdelete"},{"value":"nconf"},{"value":"nib"},{"value":"nodemon"},{"value":"v8-profiler"},{"value":"vinyl-source-stream"}]}`

**Comment by sindresorhus** [comment]
Use `console.error()` instead of `alfy.log()`. The update that improves `alfy.log()` is not out yet.
