### ISSUE TITLE
when i publish a new alfy workflow ,  they did't show a update notify

### ISSUE THREAD

**Issue by Haojen** [sindresorhus/alfy#58]
when i   npm publish a new version, after that, the my alfy workflow not  notify me to update..
i don't understand what happen, so i need you help please, i m english so bad, hope you know that.

**Comment by sindresorhus** [comment]
It only checks for updates once a day.

**Comment by SamVerschueren** [comment]
Still works:

<img width="694" alt="screen shot 2017-07-07 at 21 21 57" src="https://user-images.githubusercontent.com/1913805/27973434-547aecfc-635a-11e7-8e0c-bf4b31fa7f30.png">

Let us know if you waited at least 24 hours and still experience the same issue.
