### ISSUE TITLE
Add possibility to fetch from network with caching

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/alfy#6]
We already discussed something like this here https://github.com/sindresorhus/alfy/pull/4#issuecomment-232054583.

Here's a small wrap-up. We want to add `got` to `alfy` by default in order to make network requests. But not only that, it should be possible to cache the network requests. If later on, the same network request is performed and the cache is still valid, the cache will be returned. If the cache is not valid, a new network request is performed and the cache is updated.

Bonus feature: If the cache is not valid BUT the network request fails (user might be working offline), the cached data is still returned.

```js
alfy.fetch('https://myapi.com/foo/bar.json', {maxAge: 5000}).then(res => {
    console.log(res.body);
    // {foo: 'bar'}
});
```

Some extra notes: `fetch` is just calling `got`. So you can just pass the `method` property with value `POST` if a post request has to be performed.

@sindresorhus Did I cover everything?

**Comment by sindresorhus** [comment]
:+1: Exactly.
