### ISSUE TITLE
[ERROR: input.scriptfilter] JSON error: JSON text did not start with array or object and option to allow fragments not set.

### ISSUE THREAD

**Issue by selrond** [sindresorhus/alfy#64]
Alfred v3.5 [876]

Having this in my `index.js`, 
```js
"use strict";

const alfy = require("alfy");
const myConfig = require("./src/config.js");

alfy.output([
	{
		title: "Unicorn"
	},
	{
		title: "Rainbow"
	}
]);
```

I'm getting an error in Alfred debugger:

```shell
[ERROR: input.scriptfilter] JSON error: JSON text did not start with array or object and option to allow fragments not set. in JSON:
called
{
	"items": [
		{
			"title": "Unicorn"
		},
		{
			"title": "Rainbow"
		}
	]
}
```

If I require __custom file__ `const myConfig = require("./src/config.js");`, error __does__ show up.
If I require __npm package__ (for example `const notifier = require("node-notifier");`), error __does not__ show up.

Content of my `config.js`:
```js
const alfy = require('alfy');

const config = alfy.config;

const getTimerObject = () => {
	return config.get('timerObject') || null;
};

const setTimerObject = newTimerObject => {
	config.set('timerObject', newTimerObject);
	return getTimerObject();
};

console.log('called');

module.exports = {
	setTimerObject,
	getTimerObject
};

```

Any way I can solve this?

**Comment by SamVerschueren** [comment]
Remove the `console.log('called');` line. As you can see in your output, that is what is printed first to Alfred. What `alfy.output` does is basically just a `console.log` which Alfred parses internally and displays the items to the screen. `called` is not something he recognises so he fails.

**Comment by selrond** [comment]
@SamVerschueren removed it, now i have:
`index.js`
```javascript
"use strict";

const alfy = require("alfy");
const notifier = require("node-notifier");
const myConfig = require("./src/config.js");

myConfig.setTimerObject(alfy.input);

alfy.log(myConfig.getTimerObject());
```

`config.js`
```javascript
const alfy = require("alfy");

const config = alfy.config;

const getTimerObject = () => {
	return config.get("timerObject") || null;
};

const setTimerObject = newTimerObject => {
	config.set("timerObject", newTimerObject);
	return getTimerObject();
};

module.exports = {
	setTimerObject,
	getTimerObject
};
```

Same error...

**Comment by SamVerschueren** [comment]
Can you show the debug output?

**Comment by selrond** [comment]
@SamVerschueren here it is:

```
[2017-09-28 09:08:03][input.scriptfilter] Queuing argument 'a'
[2017-09-28 09:08:03][input.scriptfilter] Queuing argument 'asd'
[2017-09-28 09:08:05][input.scriptfilter] Script with argument 'asd' finished
[2017-09-28 09:08:05][input.scriptfilter] asd
[2017-09-28 09:08:05][ERROR: input.scriptfilter] JSON error: JSON text did not start with array or object and option to allow fragments not set. in JSON:
asd
```

**Comment by selrond** [comment]
@SamVerschueren 
The whole repo is here: 
https://github.com/selrond/alfred-standup

**Comment by selrond** [comment]
@SamVerschueren Can I help it you in any other way?

**Comment by SamVerschueren** [comment]
Make sure `alfy.output` gets an array like this one

```
alfy.output([{
	title: 'Unicorn'
}, {
	title: 'Rainbow'
}]);
```

Any other value will fail because this is an array of individual items that Alfred will render.

**Comment by SamVerschueren** [comment]
If I quickly look at your code, you are getting input from the user, being `afd` for example and just outputting it as is. That won't work like said here above, it accepts an array of Alfred items.

**Comment by selrond** [comment]
Thank you for your help! Turns out I needed to read through Alfy's methods input / output types. Also, reading the [`index.js`](https://github.com/sindresorhus/alfy/blob/master/index.js) helps a lot.
