### ISSUE TITLE
slow to exit

### ISSUE THREAD

**Issue by robjtede** [sindresorhus/alfy#70]
While testing I've found that there's a noticable lag after the script outputs the final JSON. My solution was to add a `.then(() => process.exit(0))` which speeded up results being outputted since Alfed seems to wait for the script to exit before returning anything.

**Comment by SamVerschueren** [comment]
Can you reinstall `alfy` and check if this is still the case I updated a dependency which was the root cause of this. Now this is working correctly for me.

**Comment by robjtede** [comment]
Do you know which dependency?

**Comment by SamVerschueren** [comment]
`alfred-notifier`. It gets updated automatically due to semver.

**Comment by SamVerschueren** [comment]
@robjtede can we close this one?

**Comment by robjtede** [comment]
Think so, haven’t noticed it since. Good work 👍🏻
