### ISSUE TITLE
How to copy output to clipboard?

### ISSUE THREAD

**Issue by jacc** [sindresorhus/alfy#71]
This repo hasn't gotten a commit in a month so I'm assuming it won't get a response, but I might as well try.

```js
alfy.output(
	[{
		title: `👏🏻 ${alfy.input.replace(/ /g, ' 👏🏻 ')} 👏🏻 `,
	}]);

```

This is my code. How do I copy the `title` to the clipboard?

![screen shot 2017-11-22 at 8 38 53 pm](https://user-images.githubusercontent.com/6956351/33156181-2ff9e900-cfc5-11e7-80c9-62341767fcb3.png)

That's my workflow. What am I doing wrong?

**Comment by jacc** [comment]
Pinging @SamVerschueren (so sorry for the ping)

**Comment by sindresorhus** [comment]
> This repo hasn't gotten a commit in a month so I'm assuming it won't get a response

No, won't get a response because the issue tracker is for actual issues, not support questions. It's also a little bit annoying when people assume a project is stale just based on the last commit date. This project is mature and stable and it doesn't need frequent commits.

This is a better place for support questions: https://www.alfredforum.com :)

**Comment by SamVerschueren** [comment]
And if you still think a project is stale based on commit date, here you go: 3 days ago I fixed an issue in a dependency ([alfred-notifier](https://github.com/SamVerschueren/alfred-notifier/commits/master)).

Also, if you searched the docs, you would've found [alfred-emoj](https://github.com/sindresorhus/emoj)
<img width="276" alt="screen shot 2017-11-23 at 07 29 16" src="https://user-images.githubusercontent.com/1913805/33160888-43061be4-d020-11e7-80e3-65d82b5798ea.png">

Seems a lot like what you're trying to do ;)

**Comment by jacc** [comment]
@sindresorhus @SamVerschueren My sincerest apologies, I didn’t realize these were resources. Please forgive me, you guys are like my coding heros and I love everything you do. Thank you so much!!
