### ISSUE TITLE
When use nvm,got `Couldn\'t find the `node` binary`

### ISSUE THREAD

**Issue by sinoon** [sindresorhus/alfy#73]
![image](https://user-images.githubusercontent.com/6065488/33596013-2de85f7e-d9d5-11e7-803f-c1b7bd277920.png)

when using nvm , the path of node is not sure  all the time ...

Could i pass a node path to script of `run-node.sh`?
or Tell script use the path of `nvm`?

**Comment by sinoon** [comment]
Oh , I find i can explicit the path of node . 
![image](https://user-images.githubusercontent.com/6065488/33601085-21df1716-d9e6-11e7-94c9-55788fcc03b6.png)

I think it will be convenience that how to set node path in the `README` file.

close #73

**Comment by SamVerschueren** [comment]
I use `nvm` and it works perfectly fine on my machine. `run-node` should take care of that. My node version is on the exact same location. Can you print the output of `nvm ls`? Maybe it's failing because you don't have a default setup.

**Comment by alexlafroscia** [comment]
I'm using `asdf` (similar to `nvm`) and haven't had any issues with discovering the Node version either.

**Comment by kerraway** [comment]
I use zsh-nvm https://github.com/lukechilds/zsh-nvm install nvm, and have the same problem.
So I remove .nvm folder, and disabled zsh-nvm plugin, then reinstall nvm by brew command, and add those configs into my .zshrc file:
```shell
export NVM_DIR="$HOME/.nvm"
  [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
  [ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion
```
Then reinstall alfre-workflow by npm command, and problem was gone.

I think it maybe zsh-nvm's bug.🙃️
