### ISSUE TITLE
Logging prevents results from appearing

### ISSUE THREAD

**Issue by alexlafroscia** [sindresorhus/alfy#74]
If I use `alfy.log` in my script, I can't get any valid results in the workflow. I get an error like this when trying to log some results during development:

```
[2017-12-07 15:27:10][ERROR: input.scriptfilter] JSON error: No string key for value in object around character 4. in JSON:
```

I know that `alfy.log` just goes to `STDOUT` (though `console.error`); is the issue that Alfred is reading that and trying to parse it for results? Or something in the way that my workflow is configured?

**Comment by sindresorhus** [comment]
It was fixed a long time ago (https://github.com/sindresorhus/alfy/commit/afeae0a14c36112f91bec20aeff180e65a6134ab), but we haven't done a new release since. I just did though.

**Comment by alexlafroscia** [comment]
Awesome, thanks!
