### ISSUE TITLE
Extract and open source `run-node.sh`?

### ISSUE THREAD

**Issue by kentcdodds** [sindresorhus/alfy#8]
This would help with an issue we've had for a long time on [`ghooks`](https://github.com/gtramontina/ghooks/issues/40).

I'd be happy to do it. I notice there's some specific Alfred stuff in there. Do you have any tips on how to make it in a way that works cross-platform and agnostic of Alfred?

**Comment by sindresorhus** [comment]
Hah, yeah. I already have it done. Just haven't had time to publish it yet. Will do so later tonight and let you know ;)

**Comment by kentcdodds** [comment]
That's fantastic! <3

**Comment by sindresorhus** [comment]
![cat-working-hard](https://cloud.githubusercontent.com/assets/170270/16896335/cce08310-4b90-11e6-8824-9176d1a4a028.gif)

....aaaand done: https://github.com/sindresorhus/run-node

**Comment by kentcdodds** [comment]
Awesome! [This](https://github.com/sindresorhus/run-node/blob/master/run-node#L7) doesn't work on widows right? Just a UNIX solution?

**Comment by sindresorhus** [comment]
It's a Bash script, so nothing in that script would work on Windows, unless you have "Bash on Windows" (which I have no idea how works). Happy to accept a PR for Windows support in some form, but I'm not gonna spend any time on that myself.

**Comment by kentcdodds** [comment]
Sounds good
