### ISSUE TITLE
non-bundlable with webpack

### ISSUE THREAD

**Issue by robjtede** [sindresorhus/alfy#83]
I've tried webpack, parcel, rollup and they all seem to fail at some stage.

I've gotten webpack to work by altering the way `conf` and `cache-conf` are given parentDir. By passing this explicitly in the constructor instead of relying on the `module.parent` object, webpack can resolve almost* all of the dependencies.

From `conf/index.js:21`
```js
opts = Object.assign({
  projectName: pkgPath && JSON.parse(fs.readFileSync(pkgPath, 'utf8')).name
}, opts);
```
to
```js
opts = Object.assign({
  projectName: opts.name
}, opts);
```

almost* refers to a dynamic require of `electron` in the `got` package. `got/index.js:91`

**Comment by sindresorhus** [comment]
That’s not really a concern of this module. It’s a Node.js module. It’s up to you to solve how to use it outside its intended use-case. Webpack has the `externals` option for things like this.
